#!/usr/bin/python
#https://stackoverflow.com/questions/5633828/convert-html-to-an-image-in-python in case we need to convert html to png image for mosdepth
import glob
import sys
import os

project = config['project']

coverage_dir = 'coverage'
CONTROLS = ['PLCO', 'ACS', 'LC_IGC', 'CTRL']

def getReport(wildcards):
    return glob.iglob(project + '/*_coverage_report.txt', recursive=False)

rule all:
    input:
        png_ave_depth = coverage_dir + '/Average_Coverage_caco.png',
        png_mosdepth = coverage_dir + '/mosdepth_total_dist.html'
		
rule mosdepth:
    input:
        project + '/mosdepth_dist.html'
    output:
        coverage_dir + '/mosdepth_total_dist.html'
    run:
        with open(output[0], 'w') as out, open(input[0]) as f:
            for line in f:
                if not ('chr' in line):
                    out.write(line)

rule average_depth_caco:
    input:
        getReport
    output:
        coverage_dir + '/Average_Coverage_caco.txt'
    run:
        with open(output[0], 'w') as out, open(input[0]) as f:
            out.write( 'STATUS\tCOV' + '\n' )
            next(f)
            for line in f:
                SAMPLE=line.split('\t')[3]
                DEPTH=line.split('\t')[24].rstrip()
                if not any (CONTROL in line for CONTROL in CONTROLS):
                    out.write( '1\t' + DEPTH + '\n' )
                else:
                    out.write( '2\t' + DEPTH + '\n' )
     
rule average_depth_plot:
    input:
        coverage_dir + '/Average_Coverage_caco.txt'
    output:
        png_aveCov = coverage_dir + '/Average_Coverage_caco.png',
        R = coverage_dir + '/average_depth_plot.R',
        Rout = coverage_dir + '/average_depth_plot.R.out'
    run:
        rTxt = '''
        data_coverage <- read.table("''' + str(input) + '''", header = TRUE, sep = "\t")
        colors <- c(rgb(0, 0, 1, .3), rgb(1, 0, 0, .3), rgb(.75, .75, .75, .3), rgb(0, 1, 0, .3))
        sortData <- data_coverage[with(data_coverage, order(data_coverage$STATUS,data_coverage$COV)), ]
        png("''' + str(output.png_aveCov) + '''")
        plot(sortData$COV, xlab="Samples", ylab="Average Coverage", pch=20, col= colors[sortData$STATUS], cex = 0.4)
        title(main= "Sample Coverage across Whole Exome Capture Region",sub= "", cex=0.6)
        legend("topright", legend = c("Cases", "Controls"), col = c("blue", "red"), pch = 19, cex=0.7, bty="n")
        '''
        with open(output.R, 'w') as R:
            R.write(rTxt)
        shell('R --vanilla < {output.R} > {output.Rout}')

