#!/usr/bin/python
import sys
import os

rule run_filter:
    input:
        ensemble_vcf
    output:
        vcf = postcalling_qc_dir + '/variants_annotated_majority_intersect.vcf'
    params:    
        bed = '--regions-file ' + bedFile if (config['MODE'] == 'wes') else []
    shell:
        '. /etc/profile.d/modules.sh; module load bcftools;'
        #'''cat {input} | java -Xmx16g -jar /DCEG/CGF/Bioinformatics/Analysis/public_v2/snpEff/SnpSift.jar filter "( ( FILTER =~ '2') | ( FILTER =~ '3') )" | java -Xmx16g -jar /DCEG/CGF/Bioinformatics/Analysis/public_v2/snpEff/SnpSift.jar intervals {params.bed} > {params.vcf};'''
        'bcftools view {params.bed} -f threeCallers,twoCallers -Ov -o {output.vcf} {input};'
