#!/usr/bin/python
#import glob
import sys
import os
from glob import glob

rule myfastqc:
    input:
        getBam
    output:
        'fastqc/{sample}_fastqc.html'
    params:
        outdir = 'fastqc',
        tmpdir = '/scratch/luow2/fastqc'
    shell:
        '. /etc/profile.d/modules.sh; module load fastqc;'
        'fastqc -o {params.outdir} -f bam {input} -d {params.tmpdir}'

rule multiqc:
    input:
        expand('fastqc/{sample}_fastqc.html', sample = SAMPLES)
    output:
        'fastqc/multiqc_report.html'
    params:
        outdir = 'fastqc'    
    shell:
        '. /etc/profile.d/modules.sh; module load python/2.7.8;'
        'cd fastqc; /DCEG/Resources/Tools/python/2.7.8-shared/bin/multiqc -d -s .'

