#!/usr/bin/python
import sys
import os

if config['MODE'] == 'somatic':
    rule run_filter_somatic:
        input:
            ensemble_dir + '/{sample}_5callers_voting_PASS.vcf'
        output:
            postcalling_qc_dir + '/{sample}_intersection_region_passed.recode.vcf'
        params:
            bed = bedFile,
            prefix = postcalling_qc_dir + '/{sample}_intersection_region_passed'
        shell:
            '. /etc/profile.d/modules.sh; module load vcftools;'
            '''awk -F"\t" '{{if ( $1 ~ "^#" || $7 ~ "PASS;" ){{print}}}}' {input} | vcftools --vcf - --bed {params.bed}  --recode --recode-INFO-all --out {params.prefix};'''

else:
    rule run_filter:
        input:
            ensemble_vcf
        output:
            vcf = postcalling_qc_dir + '/variants_annotated_majority_intersect.vcf.gz',
            index = postcalling_qc_dir + '/variants_annotated_majority_intersect.vcf.gz.tbi'
        params:    
            bed = '--regions-file ' + bedFile if (config['MODE'] == 'wes') else []
        shell:
            '. /etc/profile.d/modules.sh; module load bcftools tabix;'
            #'''cat {input} | java -Xmx16g -jar /DCEG/CGF/Bioinformatics/Analysis/public_v2/snpEff/SnpSift.jar filter "( ( FILTER =~ '2') | ( FILTER =~ '3') )" | java -Xmx16g -jar /DCEG/CGF/Bioinformatics/Analysis/public_v2/snpEff/SnpSift.jar intervals {params.bed} > {params.vcf};'''
            'bcftools view {params.bed} -f threeCallers,twoCallers -Oz -o {output.vcf} {input}; tabxi -p vcf {output.vcf}'
