#!/usr/bin/python
import glob
import sys
import os
from glob import glob

project = config['project']
bamDir = project + '/../bam_location/*'
ancestry_check_dir = 'laser'
hgdpDir = ancestry_check_dir + 'HGDP'
refFile = config['ref']

SAMPLES=[]

for bam in glob.iglob(bamDir + '/*.bam', recursive=True):
    samp = os.path.basename(bam)[:-4]
    SAMPLES.append(os.path.basename(bam)[:-4])

rule all:
    input:
        ancestry_check_dir + '/Results_on_HGDP938.png'

rule mpileup:
    input:
        bam = bamDir + '/{sample}.bam',
        bed = hgdpDir + 'HGDP_938.bed',
        reference = ref
    output:
        ancestry_check_dir + 'mpileup/{sample}_hgdp.mpileup'
    shell:
        '. /etc/profile.d/modules.sh; module load samtools;'
        'samtools mpileup -q 30 -Q 20 -f {input.reference} -l {input.bed} {input.bam} > {output}'

rule pileup2seq:
    input:
        expand(bamDir + '/{sample}.bam',sample = SAMPLES)
    output:
        ancestry_check_dir + '/pileup2seq_output_HGDP_938.seq'
    params:
        captureKit = config['capturekit'],
        out_prefix = pileup2seq_output_HGDP_938,
        reference = ref,
        site = hgdpDir + 'HGDP_938.site'
    threads:
        8
    shell:
        '. /etc/profile.d/modules.sh; module load python/2.7.8;'
        'python /DCEG/Resources/Tools/laser/LASER-2.04/pileup2seq/pileup2seq -f {params.reference} -m {params.site} -b {params.captureKit} -o {params.out_prefix} {input}'

rule laser_coord:
    input:
        ancestry_check_dir + '/pileup2seq_output_HGDP_938.seq'
    output:
        ancestry_check_dir + '/test_HGDP_938.RefPC.coord'
    params:
        hgdpDir + '/example.conf'
    shell:
        '. /etc/profile.d/modules.sh; module load laser;'
        'laser -p {params} -s {input} -pca 1'

rule laser_final:
    input:
        seq = ancestry_check_dir + '/pileup2seq_output_HGDP_938.seq',
        coord = ancestry_check_dir + '/test_HGDP_938.RefPC.coord'
    output:
        ancestry_check_dir + '/test_HGDP_938.SeqPC.coord'
    params:
        hgdpDir + '/example.conf'
    shell:
        '. /etc/profile.d/modules.sh; module load laser;'
        'laser -p {params} -s {input.seq} -c {input.coord}'

rule laser_plot:
    input:
        ref = ancestry_check_dir + '/test_HGDP_938.RefPC.coord',
        data = ancestry_check_dir + '/test_HGDP_938.SeqPC.coord'
    output:
        ancestry_check_dir + '/Results_on_HGDP938.png'
    shell:
        '. /etc/profile.d/modules.sh; module load R;'
        'Rscript --vanilla /CGF/Bioinformatics/Production/Wen/20180911_snakemake_coverage_tools/ExomeQcPipeline/laser/plot/plotHGDP_snakemake.r'


