#!/usr/bin/python

project = config['project']

exomeCQA_dir = 'exomeCQA'

rule all:
    input:
        summary_ue = exomeCQA_dir + '/summary_ue.txt',
        summary_ccs = exomeCQA_dir + '/summary_ccs.txt',	
        png_ue = exomeCQA_dir + '/unevenness.png',
        png_ccs = exomeCQA_dir + '/cohort_coverage_sparseness.png'
		
rule exomeCQA_exon_score:
    input:
        project + '/exomeCQA_exon.chrALL'
    output:
        exomeCQA_dir + '/exomeCQA_exon_score.chrALL'
    run:
        with open(output[0], 'w') as out:
            with open(input[0]) as f:
                for line in f:
                    list=[line.split('\t')[0],line.split('\t')[3],line.split('\t')[8],line.split('\t')[15]]
                #lines=f.readlines()
                #for x in lines:
                    out.write('\t'.join(list)+"\n")
					
rule exomeCQA_plot:
    input:
        exomeCQA_dir + '/exomeCQA_exon_score.chrALL'
    output:
        summary_ue = exomeCQA_dir + '/summary_ue.txt',
        summary_ccs = exomeCQA_dir + '/summary_ccs.txt',
        png_ue = exomeCQA_dir + '/unevenness.png',
        png_ccs = exomeCQA_dir + '/cohort_coverage_sparseness.png',
        R = exomeCQA_dir + '/exomeCQA_plot.R',
        Rout = exomeCQA_dir + '/exomeCQA_plot.R.out'
    run:
        rTxt = '''
        data_exomeCQA <- read.table("''' + str(input) + '''", header = FALSE, sep = "\t")
        sink("''' + str(output.summary_ccs) + '''")
        print(summary(data_exomeCQA[,3]))
        sink() 
        sink("''' + str(output.summary_ue) + '''")
        print(summary(data_exomeCQA[,4]))
        sink() 
        png("''' + str(output.png_ue) + '''")
        boxplot(data_exomeCQA[,4], ylab = "Unevenness (UE) Scores ")
        dev.off()
        png("''' + str(output.png_ccs) + '''")
        boxplot(data_exomeCQA[,3], ylab = "Cohort Coverage Sparseness")
        dev.off()
        '''
        with open(output.R, 'w') as R:
            R.write(rTxt)
        shell('R --vanilla < {output.R} > {output.Rout}')

