#!/usr/bin/python
import os

outName = os.path.basename(os.path.dirname(config['project']))

rule word_doc:
    input:
        template = config['doc_template'],
        contamination_plot = 'bamContamination/bam_contamination_rate.png',
        aveCov_plot = 'coverage/Average_Coverage_caco.png', 
#        mosdepth_plot = 'coverage/mosdepth_total_dist.html',
        lane_dup_plot = 'deduplication/lane_dup_rate.png',
        subject_dup_plot = 'deduplication/subject_dup_rate.png',
        fold80_plot = 'precalling_qc/fold80.png',
        seqArtifact_plot = 'precalling_qc/seq_artifact.png',
        seqArtifact_samp_count = 'precalling_qc/lowest_predatpter_baitbias_sample.csv',		
        summary_ccs_ue = 'exomeCQA/summary_ccs_ue.csv',
        ccs_plot = 'exomeCQA/cohort_coverage_sparseness.png',
        ue_plot = 'exomeCQA/unevenness.png',
        total_count = 'postcalling_qc/variant_count.png',
        titv_ratio = 'postcalling_qc/titv_ratio.png',
        lowqual_basechange = 'postcalling_qc/lowqual_basechange.png'
    output:
        doc = 'word_doc/' + outName + '_QC_Report.docx', 
        R = 'word_doc/doc.R',
        Rout = 'word_doc/doc.R.out'
    run:
        rTxt = '''library(officer)
library(magrittr)
library(flextable)
seqArtifact_samp_count <- read.csv("''' + input.seqArtifact_samp_count + '''", header = FALSE)
table_precalling <- data.frame(seqArtifact_samp_count)
names(table_precalling) <- c("Tpye", "1st Lowest", "1st Count", "2nd Lowest", "2nd Count", "3rd Lowest" ,"3rd Count")

ft_1 <- regulartable(table_precalling, col_keys = names(table_precalling)) %>%
    fontsize(size = 8, part = "all") %>%
    fontsize(i = 1, size = 10, part = "header") %>%
    color(i = 1, color = "#007FA6", part = "header") %>%
    theme_zebra(odd_header = "transparent", even_header = "transparent") %>%
    autofit()
ft_1 <- align(ft_1, align = "center")

double_format <- function(x){
  sprintf("%.2f", x)
}

summary_ccs_ue <- read.csv("''' + input.summary_ccs_ue + '''", header=TRUE,row.names=1)
table_exomeCQA <- data.frame(summary_ccs_ue)
names(table_exomeCQA) <- c( "Min", "1st.Qu", "Median", "Mean", "3rd.Qu", "Max")

ft_2 <- regulartable(table_exomeCQA, col_keys = names(table_exomeCQA)) %>%
    set_formatter("Min" = double_format, "1st.Qu" = double_format, "Median" = double_format, "Mean" = double_format, "3rd.Qu" = double_format, "Max" = double_format) %>%
    fontsize(size = 8, part = "all") %>%
    fontsize(i = 1, size = 10, part = "header") %>%
    color(i = 1, color = "#007FA6", part = "header") %>%
    theme_zebra(odd_header = "transparent", even_header = "transparent") %>%
    autofit()
ft_2 <- align(ft_2, align = "center")


my_doc <- read_docx(path = "''' + input.template + '''")  %>%
    cursor_reach(keyword = "Figure 1. sorted contamination rate by sample") %>%
    slip_in_img(src = "''' + input.contamination_plot + '''", width = 5, height = 5, pos = "before") %>%
    cursor_reach(keyword = "Figure 1. the scatter plot for all exome samples, case control separated") %>%
    slip_in_img(src = "''' + input.aveCov_plot + '''", width = 5, height = 5, pos = "before") %>%
    cursor_reach(keyword = "Figure 2. the mosdepth coverage distribution plot") %>%

    cursor_reach(keyword = "Figure 3. the boxplot for all Fold 80 base panelty for samples") %>%
    slip_in_img(src = "''' + input.fold80_plot + '''", width = 5, height = 5, pos = "before") %>%
    cursor_reach(keyword = "Figure 5. the boxplot of Lowest Preadapter and Baitbias Total Score for all samples") %>%
    slip_in_img(src = "''' + input.seqArtifact_plot + '''", width = 5, height = 5, pos = "before") %>%
    cursor_reach(keyword = "Table1.Top 3 lowest total preadatper and baitbias score base changes and number of samples having the base change as the potential artifact") %>%
    body_add_flextable(value = ft_1) %>%	
    cursor_reach(keyword = "Table2. Min, 1st quantile, Median, Mean, 3rd quantile and Max score for all exon regions") %>%
    body_add_flextable(value = ft_2) %>%
    cursor_reach(keyword = "Figure 6. the boxplot of UE score and CSS Score for all exons") %>%
    slip_in_img(src = "''' + input.ccs_plot + '''", width = 3, height = 3, pos = "before") %>%
    slip_in_img(src = "''' + input.ue_plot + '''", width = 3, height = 3, pos = "before") %>%
    cursor_reach(keyword = "Figure 8a. lane level duplication rate by sample") %>%
    slip_in_img(src = "''' + input.lane_dup_plot + '''", width = 5, height = 5, pos = "before") %>%
    cursor_reach(keyword = "Figure 8b. subject level duplication rate by sample") %>%
    slip_in_img(src = "''' + input.subject_dup_plot + '''", width = 5, height = 5, pos = "before") %>%
    cursor_reach(keyword = "Figure 9a. Ensemble filtered variant count by sample") %>%
    slip_in_img(src = "''' + input.total_count + '''", width = 5, height = 5, pos = "before") %>%
    cursor_reach(keyword = "Figure 9b. Ensemble filtered variant ti/tv ratio by sample") %>%
    slip_in_img(src = "''' + input.titv_ratio + '''", width = 5, height = 5, pos = "before") %>%
    cursor_reach(keyword = "Figure 9c. Low quality base change count by sample") %>%
    slip_in_img(src = "''' + input.lowqual_basechange + '''", width = 5, height = 5, pos = "before") 
print(my_doc, target = "''' + output.doc + '''")
'''
        with open(output.R, 'w')  as R:
            R.write(rTxt)
        shell('R --vanilla < {output.R} > {output.Rout}')
    

#    slip_in_img(src = "''' + input.mosdepth_plot + '''", width = 6, height = 6, pos = "before") %>%