#!/usr/bin/python
#import glob
import sys
import os
from glob import glob

rule myfastqc:
    input:
        getBam
    output:
        'fastqc/{sample}_fastqc.html'
    params:
        outdir = 'fastqc',
        tmpdir = config['tmpDir']
    shell:
        '. /etc/profile.d/modules.sh; module load fastqc;'
        'fastqc -o {params.outdir} -f bam {input} -d {params.tmpdir}'

rule multiqc:
    input:
        expand('fastqc/{sample}_fastqc.html', sample = SAMPLES)
    output:
        'fastqc/multiqc_report.html'
    params:
        outdir = project + '/ExomeQcPipeline/fastqc'    
    singularity: "docker://ewels/multiqc:latest"
    shell:
        #'. /etc/profile.d/modules.sh; module load python/2.7.8;'
        'cd {params.outdir}; multiqc -d -s .'

